name: Impacto da RPD

on:
    push:
        branches: [ main ]  # Trigger on push to the main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest  # Specifies the runner environment

        steps:
            - name: Checkout code
              uses: actions/checkout@v2  # Checks out your repository

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'  # Specify the Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build -- --configuration production

            - name: Deploy
              run: |
                  # Add your deployment commands here. This will depend on your server setup.
                  # For example, using SCP or SSH to copy build files to your server.
                  # You might need to use actions like 'appleboy/scp-action' or 'appleboy/ssh-action'.
