name: Impacto da RPD

on:
    push:
        branches: [ main ]  # Trigger on push to the main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest  # Specifies the runner environment

        steps:
            - name: Checkout code
              uses: actions/checkout@v2  # Checks out your repository
#
#            - name: Set up Node.js
#              uses: actions/setup-node@v2
#              with:
#                  node-version: '16'  # Specify the Node.js version
#
#            - name: Install dependencies
#              run: npm install
#
#            - name: Build
#              run: npm run build -- --configuration production

            - name: Add SSH key to known_hosts
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -t rsa ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts  2>/dev/null
                chmod 644 ~/.ssh/known_hosts
                echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Add SSH key to known_hosts
              run: |
                  ssh ${{ secrets.DEPLOY_SERVER }} " hostname -A"

#            - name: Deploy
#              uses: appleboy/scp-action@master
#              with:
#                  host: ${{ secrets.DEPLOY_SERVER }}
#                  username: ${{ secrets.DEPLOY_USER }}
#                  key: ${{ secrets.DEPLOY_KEY }}
#                  port: 22
#                  source: "dist/rpd-webmap"
#                  target: "/var/www/html"
#
#            - name: Update permissions and restart Impacto da RPD App
#              uses: appleboy/ssh-action@master
#              with:
#                  host: ${{ secrets.DEPLOY_SERVER }}
#                  username: ${{ secrets.DEPLOY_USER }}
#                  key: ${{ secrets.DEPLOY_KEY }}
#                  script: |
#                      sudo chown -R www-data:www-data /var/www/html/rpd-webmap
#                      sudo chmod -R 755 /var/www/html/rpd-webmap
#                      sudo nginx -s reload
